### ISSUE TITLE
convert login and signup pages to modal popups

### ISSUE THREAD

**Issue by 1christianfelix** [1christianfelix/raynian#23]

**Comment by ronaklalwanii** [comment]
Hey @1christianfelix, Would love to work on this. Just to confirm, If user lands on login URL a modal pops up with login fields or user has to click on a button to open the modal?

**Comment by 1christianfelix** [comment]
> 

Hi, thanks for the interest, but this is a school group project. We can't let outsiders  contribute. Sorry, again.

**Comment by ronaklalwanii** [comment]
That's okay, You don't have to apologise I understand.
